#!/usr/bin/env bash

[[ "$TRACE" ]] && set -x
set -eo pipefail

vars() {
	MAINTAINER="${MAINTAINER:-Mathias Kaufmann <steigr@me.com>}"
	OWNER="${OWNER:-$(whoami)}"
	BOARD="${BOARD:-amd64-usr}"
	BUILDER_ID="${BUILDER_ID:-$(date +%s)}"
}

build_builder() {
	local tag="$1"
	Dockerdir="$(mktemp -d)"
	cp builder "$Dockerdir"
	cat <<'EO_BUILDER' | sed -e "s/%MAINTAINER%/$MAINTAINER/g" > $Dockerdir/Dockerfile 
from alpine
maintainer %MAINTAINER%
run apk add --update squashfs-tools xz curl bash
add builder /usr/local/bin/builder
entrypoint ["builder"]
EO_BUILDER
	docker build --tag "$tag" "$Dockerdir"
	rm -r "$Dockerdir"
}

jq() {
	if [[ ! -x "$(which jq)" ]]; then
		curl -sLo jq https://github.com/stedolan/jq/releases/download/jq-1.5/jq-osx-amd64
		chmod +x jq
		export PATH="$PATH:$PWD"
	fi
	$(which jq) $@
}

http_file_exists() {
	local url="$1"
	curl -sLIfo /dev/null "$url"
}

url_of() {
	local channel="$1"
	local release="$2"
	printf "http://$channel.release.core-os.net/$BOARD/$release/coreos_production_pxe_image.cpio.gz"
}

channel_of() {
	local release="$1"
	for channel in stable beta alpha; do
		http_file_exists "$(url_of "$channel" "$release")" || continue
		printf "$channel"
		break
	done
}

releases() {
	( curl -sL http://stable.release.core-os.net/amd64-usr/; \
		curl -sL http://beta.release.core-os.net/amd64-usr/; \
		curl -sL http://alpha.release.core-os.net/amd64-usr/ \
	) \
	| awk -F'a href="' '{print $2}' \
	| cut -f1 -d/ \
	| grep -v -e current -e "^$" \
	| sort \
	| uniq
}

hash_of() {
	local url="$1"
	curl -sLI "$url" \
	| grep "^x-goog-hash:" \
	| awk -F'x-goog-hash: ' '{print $2}' \
	| xargs
}

tags_of() {
	local release="$1"
	local channel="$(channel_of "$release")"
	echo "$channel"
	[[ "$channel" = "stable" ]] \
	&& echo "latest"
}

build_readme() {
	local image="$1"
	local channel="$2"
	sed \
		-e "s@%IMAGE%@$image@g" \
		-e "s@%CHANNEL%@$channel@g" \
	> coreos/README.md
}

is_latest() {
	local release="$1"
	local url="$(url_of "stable" "$release")"
	http_file_exists "$url" || return 1
	local release_hash="$(hash_of "$url")"
	local latest_hash="$(hash_of "$(url_of "stable" "current")")"
	[[ "$release_hash" = "$latest_hash" ]]
}

is_head_of() {
	local channel="$1"
	local release="$2"
	local url="$(url_of "$channel" "$release")"
	local release_hash="$(hash_of "$url")"
	local channel_head_hash="$(hash_of "$(url_of "$channel" "current")")"
	[[ "$release_hash" = "$channel_head_hash" ]]
}

build_dockerfile() {
	local release="$1"
	sed \
		-e "s@%RELEASE%@$release@g" \
		-e "s/%MAINTAINER%/$MAINTAINER/g" \
	> coreos/Dockerfile
}

restore_image() {
	local release="$1"
	local image_file="coreos-$release.tar.xz"
	cp "temp/$image_file" "coreos/$image_file"
}

build_circle_yaml() {
	local release="$image"
	sed \
		-e "s@%IMAGE%@$image@g" \
	> coreos/circle.yml
}

git_append_tag_here() {
	local tag="$1"
	git tag -d "$tag" || true
	git tag "$tag"
}

tag_image() {
	local release="$1"
	local tags="$2"
	git_append_tag_here "$release"
	git_append_tag_here "coreos/$release"
	for tag in $tags; do
		git_append_tag_here "docker/$tag"
	done
}

commit_release() {
	local release="$1"
	ls -a | xargs git add
	git commit -m "CoreOS in Docker, Release"
}

build_image() {
	local release="$1"
	build_builder "$BUILDER_ID"
	docker run --rm --tty \
		--volume "$PWD/coreos":/target \
		--env TARGET=/target --env TRACE=$TRACE \
		"$BUILDER_ID" "$release"
}

prepare_repository() {
	git init "coreos"
	echo '*.tar.xz filter=lfs diff=lfs merge=lfs -text' > coreos/.gitattributes
	echo '.git' > coreos/.dockerignore
	( cd coreos; git add -A; git commit -m "Initial commit" )
}

has_tag() {
	local tag="$1"
	git tag \
	| grep "^$tag$"
}

prepare_new_release () {
	git rm "*.tar.xz" || true
}

main() {
	[[ -e "coreos/.git" ]] \
	|| prepare_repository
	for release in $(releases); do
		( cd coreos; has_tag "$release" ) && continue
		local channel="$(channel_of "$release")"
		[[ -z "$channel" ]] && continue
		( cd coreos; git checkout "$channel" || git checkout -b "$channel" )
		( cd coreos; prepare_new_release )
		local tags="$(tags_of "$release")"
		local image="${OWNER}/coreos:$release"
		if is_head_of "$channel" "$release"; then
			image="${OWNER}/coreos:$channel"
			if [[ "$channel" = "stable" ]]; then
				is_latest "$release" && image="${OWNER}/coreos"
			fi
		fi
		cat README.md.template  | build_readme "$image" "$channel"
		cat Dockerfile.template | build_dockerfile "$release"
		cat circle.yml.template | build_circle_yaml "$image"
		[[ -s "temp/coreos-$release.tar.xz" ]] \
		&& restore_image "$release" \
		|| build_image "$release"
		( cd coreos; commit_release "$release"; tag_image "$release" "$tags" )
	done
	docker inspect "$BUILDER_ID" >/dev/null 2>/dev/null \
	&& docker rmi -f "$BUILDER_ID"
}

vars
main $@
exit $?